# Generated by Django 5.2.7 on 2025-11-13 09:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_countries_states'),
        ('payroll_management', '0002_employeemonthlypayrolldata'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalarycomponents',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='company.companies'),
        ),
    ]
