# Generated by Django 5.2.7 on 2025-11-13 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_management', '0003_employeesalarycomponents_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeemonthlypayrolldata',
            old_name='epf',
            new_name='esi',
        ),
    ]
