# Generated by Django 5.2.7 on 2025-11-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll_management', '0004_rename_epf_employeemonthlypayrolldata_esi'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemonthlypayrolldata',
            name='lop_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='employeemonthlypayrolldata',
            name='paid_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='employeemonthlypayrolldata',
            name='total_working_days',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
    ]
