# Generated by Django 5.2.7 on 2025-10-31 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('Probation', 'Probation'), ('Confirmed', 'Confirmed'), ('Notice Period', 'Notice Period')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('Full Time', 'Full Time'), ('Contract', 'Contract')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
