# Generated by Django 5.2.7 on 2025-10-31 10:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
        ('employee', '0002_employees_created_at_employees_employment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='company.companies'),
        ),
    ]
