# Generated by Django 5.2.7 on 2025-10-31 12:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_departments_created_at_departments_updated_at_and_more'),
        ('employee', '0003_employees_company'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeLeaveBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_leaves_by_type', models.DecimalField(decimal_places=2, max_digits=5)),
                ('remaining_leaves_by_type', models.DecimalField(decimal_places=2, max_digits=5)),
                ('is_cumulated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='company.leavetypes')),
            ],
            options={
                'db_table': 'employee_leave_banks',
                'unique_together': {('employee', 'leave_type')},
            },
        ),
    ]
