# Generated by Django 5.2.7 on 2025-11-04 05:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0006_salarycomponents_description_and_more'),
        ('employee', '0004_employeeleavebank'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_confirmation', models.DateField(blank=True, null=True)),
                ('work_location', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='company.departments')),
                ('designation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='company.designations')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.RESTRICT, related_name='employee_details', to=settings.AUTH_USER_MODEL)),
                ('reporting_manager', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_details',
            },
        ),
    ]
