# Generated by Django 5.2.7 on 2025-11-04 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_employeedetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='date_of_joining',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
