# Generated by Django 5.2.7 on 2025-11-05 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employees_date_of_joining'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
