# Generated by Django 5.2.7 on 2025-11-07 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_employees_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
    ]
