# Generated by Django 5.2.7 on 2025-11-06 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_employees_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='date_of_joining',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='employment_status',
            field=models.CharField(blank=True, choices=[('Probation', 'Probation'), ('Confirmed', 'Confirmed'), ('Notice Period', 'Notice Period'), ('Relieved', 'Relieved')], max_length=20, null=True),
        ),
    ]
