# Generated by Django 5.2.7 on 2025-11-07 05:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0009_alter_employees_date_of_joining'),
        ('employee', '0009_alter_employees_date_of_joining_and_more'),
    ]

    operations = [
    ]
