# Generated by Django 5.2.7 on 2025-11-07 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_merge_20251107_0507'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='employees',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
