# Generated by Django 5.2.7 on 2025-11-07 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_employeedetails_deleted_at_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employees',
            managers=[
            ],
        ),
    ]
