# Generated by Django 5.2.7 on 2025-11-11 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_countries_states'),
        ('employee', '0012_alter_employees_managers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleavebank',
            name='leave_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='company.leavetypes'),
        ),
        migrations.AlterField(
            model_name='employeeleavebank',
            name='remaining_leaves_by_type',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='employeeleavebank',
            name='total_leaves_by_type',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
