# Generated by Django 5.2.7 on 2025-11-10 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_alter_employees_managers'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='employeeleavebank',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='employeeleavebank',
            name='remaining_leaves_by_type',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
