# Generated by Django 5.2.7 on 2025-11-11 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_alter_employeeleavebank_leave_type_and_more'),
        ('employee', '0013_alter_employeeleavebank_unique_together_and_more'),
    ]

    operations = [
    ]
