# Generated by Django 5.2.7 on 2025-11-13 05:20

import employee.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0014_merge_20251111_1538'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='employeedetails',
            managers=[
                ('objects', employee.models.UserSoftDeleteManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='employees',
            managers=[
                ('objects', employee.models.UserSoftDeleteManager()),
            ],
        ),
    ]
