# Generated by Django 5.2.7 on 2025-11-13 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_alter_employeedetails_managers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeedetails',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='bank_account_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeedetails',
            name='ifsc_code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
