# Generated by Django 5.2.7 on 2025-11-14 05:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_countries_states'),
        ('employee', '0016_employeedetails_bank_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeleavebank',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='company.companies'),
        ),
    ]
