# Generated by Django 5.2.7 on 2025-11-14 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_employeeleavebank_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='street',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
