# Generated by Django 5.2.7 on 2025-11-14 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_countries_states'),
        ('employee', '0018_employees_postal_code_employees_street'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='nationality',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.countries'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='state',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='company.states'),
        ),
    ]
