# Generated by Django 5.2.8 on 2025-11-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_alter_employees_nationality_alter_employees_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeleavebank',
            name='remaining_leaves_by_type',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='employeeleavebank',
            name='total_leaves_by_type',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, null=True),
        ),
    ]
