# Generated by Django 5.2.7 on 2025-11-14 10:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0008_countries_states'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField()),
                ('to_date', models.DateField(blank=True, null=True)),
                ('leave_duration', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('leave_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('leave_description', models.CharField(blank=True, max_length=255, null=True)),
                ('leave_days_taken', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('leave_status', models.IntegerField(choices=[(0, 'Pending'), (1, 'Approved'), (2, 'Rejected'), (3, 'Revoked'), (4, 'Cancelled')], default=0)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='company.companies')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='leave_applications', to=settings.AUTH_USER_MODEL)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='company.leavetypes')),
                ('submitted_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='leave_approvals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leave_applications',
            },
        ),
    ]
