# Generated by Django 5.2.8 on 2025-11-18 07:26

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplications',
            name='leave_duration',
            field=models.DecimalField(decimal_places=1, default=Decimal('1.0'), max_digits=3),
        ),
    ]
