# Generated by Django 5.2.8 on 2025-11-18 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leave_management', '0002_alter_leaveapplications_leave_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveapplications',
            name='leave_duration',
            field=models.DecimalField(decimal_places=1, max_digits=3),
        ),
    ]
