# Generated by Django 5.2.7 on 2025-10-31 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_alter_companies_table_departments_designations_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='companies',
            table='companies',
        ),
        migrations.AlterModelTable(
            name='departments',
            table='departments',
        ),
        migrations.AlterModelTable(
            name='designations',
            table='designations',
        ),
        migrations.AlterModelTable(
            name='holidays',
            table='holidays',
        ),
        migrations.AlterModelTable(
            name='leavetypes',
            table='leave_types',
        ),
    ]
