# Generated by Django 5.2.7 on 2025-11-04 04:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0004_departments_created_at_departments_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaryComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('type', models.CharField(max_length=25)),
                ('is_mandatory', models.BooleanField(default=False)),
                ('percentage', models.CharField(blank=True, max_length=25, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='company.companies')),
            ],
            options={
                'db_table': 'salary_components',
            },
        ),
    ]
