# Generated by Django 5.2.7 on 2025-11-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_salarycomponents'),
    ]

    operations = [
        migrations.AddField(
            model_name='salarycomponents',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salarycomponents',
            name='name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='salarycomponents',
            name='percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='salarycomponents',
            unique_together={('company', 'name')},
        ),
    ]
