# Generated by Django 5.2.7 on 2025-11-19 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0009_monthlyeffectivedays'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='monthlyeffectivedays',
            table='monthly_effective_days',
        ),
    ]
